QT.zxing.VERSION = 5.0.0
QT.zxing.name = QtZXing
QT.zxing.module = Qt5ZXing
QT.zxing.libs = $$QT_MODULE_LIB_BASE
QT.zxing.includes = $$QT_MODULE_INCLUDE_BASE $$QT_MODULE_INCLUDE_BASE/QtZXing
QT.zxing.frameworks =
QT.zxing.bins = $$QT_MODULE_BIN_BASE
QT.zxing.depends = core gui
QT.zxing.uses =
QT.zxing.module_config = v2
QT.zxing.DEFINES = QT_ZXING_LIB
QT.zxing.enabled_features =
QT.zxing.disabled_features =
QT_CONFIG +=
QT_MODULES += zxing
