SYNCQT.HEADER_FILES = ../../include/QtZXing/qtzxingversion.h ../../include/QtZXing/QtZXing 
SYNCQT.HEADER_CLASSES = ../../include/QtZXing/QtZXingVersion 
SYNCQT.PRIVATE_HEADER_FILES = 
SYNCQT.INJECTED_PRIVATE_HEADER_FILES = 
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.CLEAN_HEADER_FILES = 
SYNCQT.INJECTIONS = 
