/* This file was generated by syncqt. */
#ifndef QT_QTZXING_VERSION_H
#define QT_QTZXING_VERSION_H

#define QTZXING_VERSION_STR "5.0.0"

#define QTZXING_VERSION 0x050000

#endif // QT_QTZXING_VERSION_H
